### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [churlish404/calculator-project#2]
# Feedback

## Requirements

- Deployed website
- Github Repo:
  - README.md - DONE
  - 15 commits - DONE
    - 19, Nice!
    - Nice use of short imperative commit messages :)
- Be responsive and built mobile-first, it should work on different screen widths - DONE
- Accept a minimum of 2 inputs, perform an operation and return the output. - DONE
- DO NOT USE `eval()` - DONE
- Code is highly readable (good naming and indented correctly) - DONE

### Lets Build

- A working Calculator - DONE
- Practice using Git and GitHub flow - DONE
- Apply what you are learning?
  - SCSS - DONE
  - BEM - 99% DONE

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Union-Course-Resources/blob/main/student-resources/02-javascript-typescript/calculator-marking-scheme.md)

| Category             | Score     |
| -------------------- | --------- |
| Version Control      | 10 / 10   |
| Site Output          | 35 / 45   |
| Readability          | 20 / 20   |
| Responsiveness       | 10 / 10   |
| Code Knowledge & Use | 25 / 25   |
| Total Score          | 100 / 110 |

#### Positive

- This has been a successful project / playground for you!
- Nice clear and clean classic calculator UI.
  - I love the sales pitch for desktop
- Works well across different devices.

#### Constructive

- With BEM everything that has styling applied should have a class name so you do not hit any issues with CSS specificity.
  - This means no HTML selectors in your styles, even if they are nested.
    - The only exception is any resets. Like `*` or `body`

```scss
.calculator {
  border: solid black 3px;
  background-color: #70777e;
  padding: 0.5em auto;
  height: 80vh;
  width: 80vw;
  display: block;
  border-radius: 15px;

  button {
    display: inline-block;
  }

  // OTHER STYLES
}

// SHOULD BE

.calculator {
  border: solid black 3px;
  background-color: #70777e;
  padding: 0.5em auto;
  height: 80vh;
  width: 80vw;
  display: block;
  border-radius: 15px;

  &__button {
    display: inline-block;
  }

  // OTHER STYLES
}
```

#### Positive

- I can see a solid understanding of some of the concepts we have covered so far.
  - You are using array iteration to set up your class names on your buttons
  - You are interacting with the DOM. Displaying and updating values, acting on different events & using logic encapsulated in functions to get your calculations on the page. :)
- You have the core functionality down and have started looking into the edge cases and additional functionality which is a good place to be.
- You have started to separate your logic from the DOM. This is great for unit testing.
  - `add`, `subtract` etc could be in a separate file and could be tested
- Great use of regex and you showed a clear understanding of it in the demo :D 

#### Constructive

- I would be careful with methods that update / modify a given array.
  - As a project grows he can lead to unintended consequences

```typescript
const subtract = (numberArr: number[]): number => {
  let result = numberArr[0];
  // removes start value so don't subtract off total
  numberArr.shift();
  numberArr.forEach(number => {
    // regex appending - sign to every number following first digit
    // multiply by -1 to reverse
    number = number * -1;
    result -= number;
  });
  return result;
};

const subtract = (numberArr: number[]): number => {
  let result = numberArr[0];
  const numbers = [...numberArr]; // COPY THE ARRAY
  numbers.shift();
  numbers.forEach(number => {
    // number = number * -1; NOT SURE YOU NEED THIS?
    result -= number * -1;
  });
  return result;
};
```

- You can add multiple "....."'s should be a easy fix ;)

---
